### ISSUE TITLE
Error while run generate.py

### ISSUE THREAD

**Issue by yuanshuai220** [buriburisuri/SRGAN#13]
Traceback (most recent call last):
  File "generate.py", line 60, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('asset/train/ckpt'))
  File "/home/shuai/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/shuai/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/shuai/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/shuai/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/shuai/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.

**Comment by yuanshuai220** [comment]
I have solved my problem here!
[fix bug](https://github.com/buriburisuri/SRGAN/pull/7/commits/b33d70123d60eba9d06a23d076aa5392c67d4e18)
Thanks for @Daice
