### ISSUE TITLE
 'module' object has no attribute 'global_variables'

### ISSUE THREAD

**Issue by hiram94** [buriburisuri/SRGAN#3]
I am using the latest version of tensorflow with python 2.7 and has installed sugartensor and matplotlib as required. However, when I execute 'python train.py' in anaconda tensorflow environment, it still goes wrong. How could I deal with it?
Plus, I do not really understand the words 'You can see the result ckpt files and log files in the 'asset/train' directory. Launch tensorboard --logdir asset/train/log to monitor training process.' Does it mean I have to execute 'python train.py' and wait until the work done, then excute 'tensorboard --logdir asset/train/log'? By navigating to http://127.0.1.1:6006, I just see an almost blank TensorBoard webpage and have no idea what to do.
Many thanks.

```
Extracting ./asset/data/mnist/train-images-idx3-ubyte.gz
Extracting ./asset/data/mnist/train-labels-idx1-ubyte.gz
Extracting ./asset/data/mnist/t10k-images-idx3-ubyte.gz
Extracting ./asset/data/mnist/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    .sg_conv(dim=32)
  File "/home/haiyang/anaconda2/envs/tensorflow/lib/python2.7/site-packages/sugartensor/sg_main.py", line 218, in wrapper
    for t in tf.global_variables():
AttributeError: 'module' object has no attribute 'global_variables'
```

**Comment by buriburisuri** [comment]
@hiram94 Sorry for late reply.  Tf.global_variables() only supported from tf ver 0.12.rc-01. I guess you need to update tf.

**Comment by fazalWahid56** [comment]
@buriburisuri  this solved my same problem. I upgraded to **tf v0.12.1**.

Thanks

**Comment by ryx19th** [comment]
I came across the same problem. But I can't upgrade my tf version because it has to fit cuda 7.5 on the gpu server. (I'm not a super user.) Maybe I have to figure some way else out.

**Comment by openviso** [comment]
只需把tensorflow 更新到最新版本即可

**Comment by VictorMarchenkov** [comment]
I came across the same problem. 
tensorflow 1.0.1
sugartensor 1.0.0.1

Traceback (most recent call last):
  File "/Users/victor/PycharmProjects/tensorflow_images/mnist_gan/ebgan/mnist_eb_gan_generate.py", line 28, in <module>
    gen = (z.sg_dense(dim=1024)
  File "/anaconda/lib/python3.5/site-packages/sugartensor/sg_main.py", line 218, in wrapper
    for t in tf.global_variables():
AttributeError: module 'sugartensor' has no attribute 'global_variables'

**Comment by VictorMarchenkov** [comment]
And there is problem:
Traceback (most recent call last):
  File "/Users/victor/PycharmProjects/tensorflow_images/mnist_gan/ebgan/mnist_eb_gan_generate.py", line 5, in <module>
    import sugartensor as tf
  File "/anaconda/lib/python3.5/site-packages/sugartensor/__init__.py", line 7, in <module>
    from .sg_train import *
  File "/anaconda/lib/python3.5/site-packages/sugartensor/sg_train.py", line 9, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector

ImportError: No module named 'tensorflow.contrib.tensorboard'

Solution to comment line 9 in sg_train.py because not used
