### ISSUE TITLE
Unable to get element from the feed as bytes

### ISSUE THREAD

**Issue by Cogito2012** [buriburisuri/SRGAN#5]
When I run your code generate.py, errors as follow:

`Traceback (most recent call last):
  File "generate.py", line 60, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('asset/train/ckpt'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.`

I've found similar errors when using tensorflow.
[http://stackoverflow.com/questions/41369062/tensorflow-fail-with-unable-to-get-element-from-the-feed-as-bytes-when-attemp](url)
But still don't know how to solve it...

**Comment by Daice** [comment]
I have the same problem. You solved it?

**Comment by Cogito2012** [comment]
@Daice I haven't solved it.

**Comment by Daice** [comment]
I have solved it.
https://github.com/Daice/SRGAN

**Comment by Cogito2012** [comment]
@Daice OK, thanks for your SRGAN fork, actually a small modification as follow can solve this problem:
line 60 in generate.py file:
&nbsp; &nbsp; &nbsp; &nbsp; saver.restore(sess, tf.train.latest_checkpoint('asset/train/ckpt'))
modified as:
&nbsp; &nbsp; &nbsp; &nbsp; saver.restore(sess, tf.train.latest_checkpoint('asset/train'))
